language: d

before_install:
  - sudo apt-get update
  - sudo apt-get install liblapack-dev

install:
  - wget -O doveralls https://github.com/ColdenCullen/doveralls/releases/download/v1.1.4/doveralls_linux_travis

script:
  - dub test -b unittest-cov
  - ./doveralls
